server:
    port: 9000

spring: 
    application: 
        name: acr-gateway
    
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        client-id:
                        client-secret:
                        scope: openid, profile, email
                provider:
                    keycloak:
                        issuer-uri: http://localhost:8080/ # Path a ser autenticado
    cloud:
        gateway:
            routes:
                - id: hello-application
                  uri: http://localhost:8081
                  predicates:
                    - Path=/hello/**
                  filters:
                    - TokenRelay=